### ISSUE TITLE
nasuni-edge-appliance-automation script error

### ISSUE THREAD

**Issue by agrancea** [nasuni-labs/nasuni-edgeappliance-automation#5]
nasuni-edge-appliance-automation.ps1 has a error from the start
- script downloaded and unzipped from github
- ran the scrip without referencing variables.ps1, presentation says i will be prompted for it

Thanks,
Adrian

![screenshot](https://user-images.githubusercontent.com/40340047/160668668-ae79e67d-62bc-4704-9bc9-3c2c5ad1a7e8.jpg)
r

**Comment by cdillahunty-nasuni** [comment]
Hello Adrian,

I'm sorry for the trouble. I wasn't able to reproduce the issue--PowerShell prompted me for the path to the script if I didn't reference variables.ps1:

```
PS C:\Users\Administrator> C:\scripts\AutodeployEA.ps1
Please enter the path to the variables input file:  
```


Can you run the following command so that I can see your PowerShell version?

`Get-Host | Select-Object Version`

**Comment by agrancea** [comment]
Hello Coan,

Version
-------
5.1.19041.1320

**Comment by cdillahunty-nasuni** [comment]
Hello Adrian,

The PowerShell version could be the issue. We built them and tested them to support PowerShell 6 or higher. The current PowerShell version is 7.2.2.

**Comment by agrancea** [comment]
Hello Coan,
It works like a charm in ver 7.2.2. One suggestion for improvement, prompt for credentials rather than leave them on variables file, our security team won't like admin credentials in clear text 

Thanks for your help,
Adrian

**Comment by alexanderwillacker** [comment]
...I made a wrapper around the powershell script which checks for version and retrieves credentials then I call the script.

**Comment by agrancea** [comment]
Thank you for all your help

**Comment by cdillahunty-nasuni** [comment]
closing this issue since it's resolved.
