### ISSUE TITLE
AutodeployEA script error

### ISSUE THREAD

**Issue by agrancea** [nasuni-labs/nasuni-edgeappliance-automation#6]
Hello,
Getting many errors running the script, right from the top, see attached
"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond"
[Autodeploy EA errors.docx](https://github.com/nasuni-labs/nasuni-edgeappliance-automation/files/8532278/Autodeploy.EA.errors.docx)

I would appreciate your help to troubleshoot. 

Thanks,
Adrian Grancea | Systems Administrator
Phone: +1.416.627.1675
[adrian.grancea@tetratech.com](mailto:adrian.grancea@tetratech.com)

Tetra Tech | Enterprise Technical Support
6835A Century Avenue | Mississauga, ON L5N 7K2 | Canada | [www.tetratech.com](http://www.tetratech.com/)

**Comment by cdillahunty-nasuni** [comment]
Hello Adrian,

I'll follow up with you over email--it looks as if the variables aren't getting picked up by the script.

Coan

**Comment by cdillahunty-nasuni** [comment]
We found the source of the problem--the script expects to be executed in this way:

`./AutoDeployEA.ps1 -varPath varFile.ps1`

but was be called like this

`./AutoDeployEA.ps1 -varPath ./varFile.ps1`

Removing the "./" gave PowerShell the right path to the variable file and resolved the issue.
